### ISSUE TITLE
How do I use it? 

### ISSUE THREAD

**Issue by vanor89** [erikmueller/an-old-hype#3]
I cant seem to find a way to use it... :S

**Comment by erikmueller** [comment]
@CarlosV89 yeah, sorry I didn't put any usage descriptions in the Readme.
It's actually very simple. Open the `~/.hyper.js` file (on Mac you can simply press `Cmd + ,`) and go to the `plugins` section.

Change the empty Array to sth like this

```
plugins: ['an-old-hype']
```

Hyper should reload and use the new theme (sometimes restarting hyper is required)
Hope that helps.

Cheers

**Comment by vanor89** [comment]
It does! Tyvm
